/**
 * Custom provider for oneapi.amfibi.duckdns.org OpenAI-compatible proxy.
 * Auto-generated by gen-byan.nu — do not edit manually.
 *
 * Env vars:
 *   BYAN_BASE_URL  = https://oneapi.amfibi.duckdns.org/v1
 *   BYAN_AUTH_TOKEN = <your token>
 */
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

export default function (pi: ExtensionAPI) {
  const baseUrl =
    process.env.BYAN_BASE_URL || "https://oneapi.amfibi.duckdns.org/v1";

  const compatClaude = {
    supportsDeveloperRole: false,
    supportsReasoningEffort: false,
    maxTokensField: "max_tokens" as const,
  };

  const compatGpt = {
    supportsDeveloperRole: true,
    supportsReasoningEffort: false,
    maxTokensField: "max_completion_tokens" as const,
  };

  pi.registerProvider("byan", {
    baseUrl,
    apiKey: "BYAN_AUTH_TOKEN",
    authHeader: true,
    api: "openai-completions",
    models: [
      {
        id: "Claude Haiku 4.5",
        name: "Claude Haiku 4 5",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 200000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "Claude Opus 4.6",
        name: "Claude Opus 4 6",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 200000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "Claude Sonnet 4.5",
        name: "Claude Sonnet 4 5",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 200000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "GPT 5.1 Codex Max",
        name: "GPT 5 1 Codex Max",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 200000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "GPT 5.2 Codex",
        name: "GPT 5 2 Codex",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 200000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "GPT 5.3 Codex",
        name: "GPT 5 3 Codex",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 200000,
        maxTokens: 64000,
        compat: compatGpt,
      }
    ],
  });
}
