#!/usr/bin/env nu

# Fetches models from kosyayuk API and regenerates kosyayuk-provider.ts
# Usage: nu agents/pi/extensions/gen-kosyayuk.nu

let api_url = ($env.ANTHROPIC_BASE_URL? | default "https://ai.naufal.work")
let token = ($env.ANTHROPIC_AUTH_TOKEN? | default "")
let out_file = ($env.FILE_CUSTOM_DIR? | default ([$env.HOME "dotfiles/agents/pi/extensions/kosyayuk-provider.ts"] | path join))

if $token == "" {
  print "Error: ANTHROPIC_AUTH_TOKEN not set"
  exit 1
}

print $"Fetching models from ($api_url)/v1/models ..."

let raw = (curl -s -H $"Authorization: Bearer ($token)" $"($api_url)/v1/models" | from json)

let models = ($raw.data | sort-by id | each {|m|
  let id = $m.id

  # Determine compat type: claude models use anthropic compat, everything else uses openai compat
  let compat = if ($id =~ "claude|haiku|sonnet|opus") {
    "compatClaude"
  } else {
    "compatGpt"
  }

  # Determine reasoning
  let reasoning = if ($id | str contains "opus") {
    true
  } else if ($id =~ "sonnet-4-[56]") {
    true
  } else {
    false
  }

  # Determine input modalities
  let input = if ($id | str contains "gpt-3") {
    '["text"]'
  } else if ($id =~ "deepseek|minimax|qwen") {
    '["text"]'
  } else {
    '["text", "image"]'
  }

  # Determine context window
  let ctx = if ($id | str contains "minimax") {
    1000000
  } else if ($id =~ "qwen") {
    131072
  } else if ($id | str contains "gpt-3") {
    16384
  } else if ($id =~ "gpt|deepseek") {
    128000
  } else {
    200000
  }

  # Determine max tokens
  let max_tok = if ($id | str contains "haiku") {
    8192
  } else if ($id | str contains "gpt-3") {
    4096
  } else if ($id =~ "gpt-4|deepseek|qwen") {
    16384
  } else if ($id =~ "minimax") {
    64000
  } else {
    64000
  }

  # Determine cost ($/M tokens)
  let cost = if ($id | str contains "opus") {
    { input: 5, output: 25, cache_read: 0.5, cache_write: 6.25 }
  } else if ($id | str contains "sonnet") {
    { input: 3, output: 15, cache_read: 0.3, cache_write: 3.75 }
  } else if ($id | str contains "haiku") {
    { input: 0.8, output: 4, cache_read: 0.08, cache_write: 1 }
  } else {
    { input: 0, output: 0, cache_read: 0, cache_write: 0 }
  }

  # Build display name from id: "claude-opus-4-6" → "Claude Opus 4 6"
  let name = ($id | str replace --all "-" " " | split words | each {|w|
    let chars = ($w | split chars)
    let first = ($chars | first | str upcase)
    let rest = ($chars | skip 1 | str join "")
    $"($first)($rest)"
  } | str join " ")

  {
    id: $id
    name: $name
    reasoning: $reasoning
    input: $input
    cost: $cost
    contextWindow: $ctx
    maxTokens: $max_tok
    compat: $compat
  }
})

print $"Found ($models | length) models. Generating ($out_file) ..."

# Build the models array entries
let model_entries = ($models | each {|m|
  let reasoning_str = if $m.reasoning { "true" } else { "false" }
  $"      {
        id: \"($m.id)\",
        name: \"($m.name)\",
        reasoning: ($reasoning_str),
        input: ($m.input),
        cost: { input: ($m.cost.input), output: ($m.cost.output), cacheRead: ($m.cost.cache_read), cacheWrite: ($m.cost.cache_write) },
        contextWindow: ($m.contextWindow),
        maxTokens: ($m.maxTokens),
        compat: ($m.compat),
      }"
} | str join ",\n")

# Generate the full file
let header = '/**
 * Custom provider for ai.naufal.work OpenAI-compatible proxy.
 * Auto-generated by gen-kosyayuk.nu — do not edit manually.
 *
 * Env vars:
 *   ANTHROPIC_BASE_URL  = https://ai.naufal.work
 *   ANTHROPIC_AUTH_TOKEN = <your token>
 */
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

export default function (pi: ExtensionAPI) {
  const baseUrl =
    (process.env.ANTHROPIC_BASE_URL || "https://ai.naufal.work") + "/v1";

  const compatClaude = {
    supportsDeveloperRole: false,
    supportsReasoningEffort: false,
    maxTokensField: "max_tokens" as const,
  };

  const compatGpt = {
    supportsDeveloperRole: true,
    supportsReasoningEffort: false,
    maxTokensField: "max_completion_tokens" as const,
  };

  pi.registerProvider("kosyayuk", {
    baseUrl,
    apiKey: "ANTHROPIC_AUTH_TOKEN",
    authHeader: true,
    api: "openai-completions",
    models: ['

let footer = '    ],
  });
}
'

let ts = [$header $model_entries $footer] | str join "\n"

$ts | save -f $out_file
print $"Done! ($models | length) models written to ($out_file)"
