#!/usr/bin/env nu

# Fetches models from enowxlabs API and regenerates enowxlabs.ts
# Usage: nu agents/pi/extensions/gen-enowxlabs.nu

let api_url = ($env.ENOWX_BASE_URL? | default "http://localhost:1430")
let token = ($env.ENOWX_AUTH_TOKEN? | default "")
let out_file = ($env.FILE_CUSTOM_DIR? | default ([$env.HOME "dotfiles/agents/pi/extensions/enowxlabs.ts"] | path join))

if $token == "" {
  print "Error: ENOWX_AUTH_TOKEN not set"
  exit 1
}

print $"Fetching models from ($api_url)/v1/models ..."

let raw = (curl -s -H $"Authorization: Bearer ($token)" $"($api_url)/v1/models" | from json)

let title_case = {|value|
  $value
  | str replace --all "-" " "
  | split words
  | each {|w|
      let lower = ($w | str downcase)
      if $lower == "gpt" {
        "GPT"
      } else if $lower == "glm" {
        "GLM"
      } else if $lower == "qwen" {
        "Qwen"
      } else if $lower == "kimi" {
        "Kimi"
      } else if $lower == "claude" {
        "Claude"
      } else if $lower == "sonnet" {
        "Sonnet"
      } else if $lower == "haiku" {
        "Haiku"
      } else if $lower == "opus" {
        "Opus"
      } else if $lower == "gemini" {
        "Gemini"
      } else if $lower == "deepseek" {
        "DeepSeek"
      } else if $lower == "minimax" {
        "MiniMax"
      } else if $lower == "enowx" {
        "enowX"
      } else if ($w | str contains ".") or ($w | str contains "_") or ($w =~ '^[0-9]+$') {
        $w
      } else {
        let chars = ($w | split chars)
        let first = ($chars | first | str upcase)
        let rest = ($chars | skip 1 | str join "")
        $"($first)($rest)"
      }
    }
  | str join " "
}

let models = ($raw.data | sort-by id | each {|m|
  let id = $m.id
  let compat = if ($id =~ "claude|haiku|sonnet|opus") {
    "compatClaude"
  } else {
    "compatGpt"
  }

  let input = if ($id =~ "deepseek|minimax|glm|qwen|kimi|enowx-default") {
    '["text"]'
  } else {
    '["text", "image"]'
  }

  let ctx = if ($id =~ "gemini") {
    1048576
  } else if ($id =~ "gpt-5") {
    256000
  } else if ($id =~ "minimax") {
    1000000
  } else if ($id =~ "qwen|kimi") {
    131072
  } else if ($id =~ "deepseek|glm|enowx-default") {
    128000
  } else {
    200000
  }

  let max_tok = if ($id =~ "haiku") {
    8192
  } else if ($id =~ "deepseek|glm|qwen|kimi|enowx-default") {
    16384
  } else if ($id =~ "gemini") {
    65536
  } else {
    64000
  }

  let name = ($m.name? | default (do $title_case $id))

  {
    id: $id
    name: $name
    reasoning: true
    input: $input
    contextWindow: $ctx
    maxTokens: $max_tok
    compat: $compat
  }
})

print $"Found ($models | length) models. Generating ($out_file) ..."

let model_entries = ($models | each {|m|
  $"      {
        id: \"($m.id)\",
        name: \"($m.name)\",
        reasoning: true,
        input: ($m.input),
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: ($m.contextWindow),
        maxTokens: ($m.maxTokens),
        compat: ($m.compat),
      }"
} | str join ",\n")

let header = '/**
 * Custom provider for enowxlabs OpenAI-compatible proxy.
 * Auto-generated by gen-enowxlabs.nu — do not edit manually.
 *
 * Env vars:
 *   ENOWX_BASE_URL = http://localhost:1430
 *   ENOWX_AUTH_TOKEN = <your token>
 */
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

export default function enowxlabs(pi: ExtensionAPI) {
  const baseUrl =
    (process.env.ENOWX_BASE_URL || "http://localhost:1430") + "/v1";

  const compatClaude = {
    supportsDeveloperRole: false,
    supportsReasoningEffort: false,
    maxTokensField: "max_tokens" as const,
  };

  const compatGpt = {
    supportsDeveloperRole: true,
    supportsReasoningEffort: false,
    maxTokensField: "max_completion_tokens" as const,
  };

  pi.registerProvider("enowxlabs", {
    baseUrl,
    apiKey: "ENOWX_AUTH_TOKEN",
    authHeader: true,
    api: "openai-completions",
    models: ['

let footer = '    ],
  });
}
'

let ts = [$header $model_entries $footer] | str join "\n"

$ts | save -f $out_file
print $"Done! ($models | length) models written to ($out_file)"
