/**
 * Custom provider for ai.naufal.work OpenAI-compatible proxy.
 * Auto-generated by gen-kosyayuk.nu — do not edit manually.
 *
 * Env vars:
 *   ANTHROPIC_BASE_URL  = https://ai.naufal.work
 *   ANTHROPIC_AUTH_TOKEN = <your token>
 */
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

export default function (pi: ExtensionAPI) {
  const baseUrl =
    (process.env.ANTHROPIC_BASE_URL || "https://ai.naufal.work") + "/v1";

  const compatGpt = {
    supportsDeveloperRole: true,
    supportsReasoningEffort: false,
    maxTokensField: "max_completion_tokens" as const,
  };

  pi.registerProvider("kosyayuk", {
    baseUrl,
    apiKey: "ANTHROPIC_AUTH_TOKEN",
    authHeader: true,
    api: "openai-completions",
    models: [
      {
        id: "gpt-5",
        name: "Gpt 5",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "gpt-5-codex",
        name: "Gpt 5 Codex",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "gpt-5-codex-mini",
        name: "Gpt 5 Codex Mini",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "gpt-5.1",
        name: "Gpt 5 1",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "gpt-5.1-codex",
        name: "Gpt 5 1 Codex",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "gpt-5.1-codex-max",
        name: "Gpt 5 1 Codex Max",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "gpt-5.1-codex-mini",
        name: "Gpt 5 1 Codex Mini",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "gpt-5.2",
        name: "Gpt 5 2",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "gpt-5.2-codex",
        name: "Gpt 5 2 Codex",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "gpt-5.3-codex",
        name: "Gpt 5 3 Codex",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 64000,
        compat: compatGpt,
      },
      {
        id: "gpt-5.4",
        name: "Gpt 5 4",
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 128000,
        maxTokens: 64000,
        compat: compatGpt,
      }
    ],
  });
}
